

#cc -fsanitize=thread


echo 'try'
echo "Marry()"
echo "if you marry a good wife"
echo "you will be happy"
echo "if a bad wife"
echo "you will become a"
echo ""
sleep(1)
echo ""
echo "philosopher"

echo 'except SpouseNotFound'
echo 'you shall be a'
echo "Hacker!"


NAME    =  ./philo

FLAGS   =  -Wall -Wextra -Werror
RED     =  \033[31m
GREEN   =  \033[32m
YELLOW  =  \033[33m
BLUE    =  \033[34m
MAGENTA =  \033[35m
CYAN    =  \033[36m
WHITE   =  \033[37m
RESET   =  \033[0m



SRC =


